# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

2.2.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
np.random.seed(0)
a = np.random.random((2, 3, 5))
print(a.shape)

(2, 3, 5)


In [4]:
# Method 2
a = np.random.rand(2, 3, 5)
print(a.shape)

(2, 3, 5)


In [5]:
# Method 3
a = np.random.uniform(0, 1, (2, 3, 5))
print(a.shape)

(2, 3, 5)


#### 4. Print *a*.

In [6]:
print(a)

[[[0.15896958 0.11037514 0.65632959 0.13818295 0.19658236]
  [0.36872517 0.82099323 0.09710128 0.83794491 0.09609841]
  [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358]]

 [[0.03918779 0.28280696 0.12019656 0.2961402  0.11872772]
  [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145]
  [0.26538949 0.52324805 0.09394051 0.5759465  0.9292962 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
b = np.ones((5, 2, 3))
print(b.shape)

(5, 2, 3)


#### 6. Print *b*.

In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
print('a.size =', a.size)
print('b.size =', b.size)
print('Same size?', a.size == b.size)
# Yes, both have size 30 (2*3*5 = 5*2*3 = 30), even though shapes differ.

a.size = 30
b.size = 30
Same size? True


#### 8. Are you able to add *a* and *b*? Why or why not?

In [10]:
try:
    print(a + b)
except ValueError as e:
    print(type(e).__name__ + ':', e)

# Answer: No. a has shape (2, 3, 5) and b has shape (5, 2, 3).
# NumPy cannot broadcast these shapes for element-wise addition.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# b is (5, 2, 3). We need (2, 3, 5).
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
d = a + c
print(d.shape)
# It works because a and c now have the same shape (2, 3, 5),
# so element-wise addition is valid.

(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print('a:\n', a)
print('\nd:\n', d)
# Relation: since c is all ones, d = a + 1 for every element.
# Each value in d is exactly 1 greater than the corresponding value in a.

a:
 [[[0.15896958 0.11037514 0.65632959 0.13818295 0.19658236]
  [0.36872517 0.82099323 0.09710128 0.83794491 0.09609841]
  [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358]]

 [[0.03918779 0.28280696 0.12019656 0.2961402  0.11872772]
  [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145]
  [0.26538949 0.52324805 0.09394051 0.5759465  0.9292962 ]]]

d:
 [[[1.15896958 1.11037514 1.65632959 1.13818295 1.19658236]
  [1.36872517 1.82099323 1.09710128 1.83794491 1.09609841]
  [1.97645947 1.4686512  1.97676109 1.60484552 1.73926358]]

 [[1.03918779 1.28280696 1.12019656 1.2961402  1.11872772]
  [1.31798318 1.41426299 1.0641475  1.69247212 1.56660145]
  [1.26538949 1.52324805 1.09394051 1.5759465  1.9292962 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
e = a * c
print(e)

[[[0.15896958 0.11037514 0.65632959 0.13818295 0.19658236]
  [0.36872517 0.82099323 0.09710128 0.83794491 0.09609841]
  [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358]]

 [[0.03918779 0.28280696 0.12019656 0.2961402  0.11872772]
  [0.31798318 0.41426299 0.0641475  0.69247212 0.56660145]
  [0.26538949 0.52324805 0.09394051 0.5759465  0.9292962 ]]]


#### 13. Does *e* equal to *a*? Why or why not?

In [15]:
print(np.array_equal(e, a))
print(np.allclose(e, a))
# Yes. c is an array of ones with the same shape as a,
# so multiplying a * c leaves every value unchanged. Therefore e equals a.

True
True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)

1.976761088190337 1.0391877922543207 1.4182543565881527


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.

In [17]:
f = np.empty(d.shape)
print(f.shape)

(2, 3, 5)


#### 16. Populate the values in *f*.

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

In [18]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

print(np.unique(f))

[  0.  25.  75. 100.]


#### 17. Print *d* and *f*. Do you have your expected *f*?

In [19]:
print('d:\n', d)
print('\nf:\n', f)

d:
 [[[1.15896958 1.11037514 1.65632959 1.13818295 1.19658236]
  [1.36872517 1.82099323 1.09710128 1.83794491 1.09609841]
  [1.97645947 1.4686512  1.97676109 1.60484552 1.73926358]]

 [[1.03918779 1.28280696 1.12019656 1.2961402  1.11872772]
  [1.31798318 1.41426299 1.0641475  1.69247212 1.56660145]
  [1.26538949 1.52324805 1.09394051 1.5759465  1.9292962 ]]]

f:
 [[[ 25.  25.  75.  25.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75. 100.  75.  75.]]

 [[  0.  25.  25.  25.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements.

In [20]:
g = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                g[i, j, k] = 'A'
            elif value == d_max:
                g[i, j, k] = 'E'
            elif value == d_mean:
                g[i, j, k] = 'C'
            elif d_min < value < d_mean:
                g[i, j, k] = 'B'
            elif d_mean < value < d_max:
                g[i, j, k] = 'D'

print(g)

[[['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['D' 'D' 'E' 'D' 'D']]

 [['A' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']]]
